version: "2"

linters:
  default: none
  
  enable:
    - errcheck      # Check for unchecked errors
    - gosec         # Security issues
    - ineffassign   # Ineffectual assignments
    - staticcheck   # Advanced static analysis
    - govet         # Standard go vet
    - misspell      # Spelling errors
    - unused        # Finds unused code
    - revive        # Extensible linter (golint replacement)

  settings:
    errcheck:
      check-type-assertions: true
    
    gosec:
      severity: medium
      confidence: medium
    
    staticcheck:
      checks: ["all"]

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0